# Generated by Django 5.2.7 on 2025-11-04 10:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('register_number', models.CharField(max_length=100, unique=True)),
                ('umis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('address', models.TextField()),
                ('community', models.CharField(blank=True, choices=[('OC', 'Open Competition (OC)'), ('BC', 'Backward Class (BC)'), ('MBC', 'Most Backward Class (MBC)'), ('DNC', 'Denotified Communities (DNC)'), ('BCM', 'Backward Class (Muslim) (BCM)'), ('SC', 'Scheduled Caste (SC)'), ('SCA', 'Scheduled Caste (Arunthathiyar) (SCA)'), ('ST', 'Scheduled Tribe (ST)')], max_length=255, null=True)),
                ('level', models.CharField(choices=[('ug', 'UG'), ('pg', 'PG'), ('le', 'LE')], max_length=10)),
                ('department_preferences', models.JSONField(default=dict)),
                ('pg_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('tc', models.FileField(upload_to=app.models.certificate_upload_path)),
                ('community_cert', models.FileField(upload_to=app.models.certificate_upload_path)),
                ('aadhaar', models.FileField(upload_to=app.models.certificate_upload_path)),
                ('tenth_marksheet', models.FileField(upload_to=app.models.certificate_upload_path)),
                ('twelfth_marksheet', models.FileField(blank=True, null=True, upload_to=app.models.certificate_upload_path)),
                ('photo', models.FileField(upload_to=app.models.photo_upload_path)),
                ('admission_fee', models.CharField(max_length=50)),
                ('tuition_fee', models.CharField(max_length=50)),
                ('college_fee', models.CharField(max_length=50)),
                ('hostel_fee', models.CharField(max_length=50)),
                ('bus_fee', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('payment_screenshot', models.FileField(upload_to=app.models.payment_upload_path)),
                ('tenth_total', models.CharField(max_length=50)),
                ('tenth_percentage', models.CharField(max_length=50)),
                ('twelfth_total', models.CharField(blank=True, max_length=50, null=True)),
                ('twelfth_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('group_major', models.CharField(max_length=255)),
                ('last_school', models.CharField(max_length=255)),
                ('board', models.CharField(choices=[('State Board', 'State Board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Matriculation', 'Matriculation'), ('Diploma', 'Diploma'), ('Others', 'Others')], max_length=50)),
                ('year_passing', models.IntegerField()),
                ('medium', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Others', 'Others')], max_length=50)),
                ('vocational_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_proof', models.FileField(blank=True, null=True, upload_to=app.models.vocational_upload_path)),
                ('bus_needed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('boarding_point', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_route', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_needed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('hostel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('mess_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hostel_fee_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('reference_department', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
