# Generated by Django 5.2.7 on 2025-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='cutoff_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
