# Generated by Django 5.2.7 on 2025-11-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admission_cutoff_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='Application_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
