# Generated by Django 5.2.7 on 2025-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_admission_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
