# Generated by Django 5.2.7 on 2025-11-09 16:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_admission_guardian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='aadhaar',
            field=models.FileField(blank=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='board',
            field=models.CharField(blank=True, choices=[('State Board', 'State Board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Matriculation', 'Matriculation'), ('Diploma', 'Diploma'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bus_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bus_needed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='admission',
            name='college_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='community_cert',
            field=models.FileField(blank=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='admission',
            name='department_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='admission',
            name='group_major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hostel_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hostel_needed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='admission',
            name='last_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='medium',
            field=models.CharField(blank=True, choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='payment_screenshot',
            field=models.FileField(blank=True, upload_to=app.models.payment_upload_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='photo',
            field=models.FileField(blank=True, upload_to=app.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='reference_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tc',
            field=models.FileField(blank=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_marksheet',
            field=models.FileField(blank=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_total',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tuition_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='year_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
