# Generated by Django 5.2.8 on 2025-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_admission_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='register_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
