# Generated by Django 5.2.8 on 2025-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_admission_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='chemistry_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='maths_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='physics_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='qualification',
            field=models.CharField(blank=True, choices=[('12th', '12th'), ('Diploma', 'Diploma')], max_length=10),
        ),
    ]
