# Generated by Django 5.2.8 on 2025-11-20 19:50

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_admission_chemistry_marks_admission_maths_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='board',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bus_needed',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='chemistry_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='cutoff_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='group_major',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hostel_fee_amount',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hostel_needed',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hostel_type',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_school',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='maths_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mess_type',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='physics_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_department',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_designation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_mobile',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='skill_proof',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='tenth_percentage',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='tenth_total',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='twelfth_percentage',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='twelfth_total',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='vocational_stream',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='year_passing',
        ),
        migrations.CreateModel(
            name='PaymentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=app.models.payment_upload_path)),
                ('tenth_total', models.CharField(blank=True, max_length=50)),
                ('tenth_percentage', models.CharField(blank=True, max_length=50)),
                ('twelfth_total', models.CharField(blank=True, max_length=50, null=True)),
                ('twelfth_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('12th', '12th'), ('Diploma', 'Diploma')], max_length=10)),
                ('maths_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('physics_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('chemistry_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('group_major', models.CharField(blank=True, max_length=255)),
                ('cutoff_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('last_school', models.CharField(blank=True, max_length=255)),
                ('board', models.CharField(blank=True, choices=[('State Board', 'State Board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Matriculation', 'Matriculation'), ('Diploma', 'Diploma'), ('Others', 'Others')], max_length=50)),
                ('year_passing', models.IntegerField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Others', 'Others')], max_length=50)),
                ('vocational_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_proof', models.FileField(blank=True, null=True, upload_to=app.models.vocational_upload_path)),
                ('bus_needed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('boarding_point', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_route', models.CharField(blank=True, max_length=100, null=True)),
                ('hostel_needed', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('hostel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('mess_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hostel_fee_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('reference_department', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_screenshots', to='app.admission')),
            ],
        ),
    ]
