# Generated by Django 5.2.8 on 2025-11-21 03:13

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_admission_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='board',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='bus_needed',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='chemistry_marks',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='cutoff_marks',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='group_major',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='hostel_fee_amount',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='hostel_needed',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='hostel_type',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='last_school',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='maths_marks',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='mess_type',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='physics_marks',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='reference_department',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='reference_designation',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='reference_mobile',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='skill_proof',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='tenth_percentage',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='tenth_total',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='twelfth_percentage',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='twelfth_total',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='vocational_stream',
        ),
        migrations.RemoveField(
            model_name='paymentscreenshot',
            name='year_passing',
        ),
        migrations.AddField(
            model_name='admission',
            name='board',
            field=models.CharField(blank=True, choices=[('State Board', 'State Board'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Matriculation', 'Matriculation'), ('Diploma', 'Diploma'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='bus_needed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='admission',
            name='bus_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='chemistry_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='cutoff_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='group_major',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_fee_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_needed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='last_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='maths_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='medium',
            field=models.CharField(blank=True, choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='mess_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_screenshot',
            field=models.FileField(blank=True, upload_to=app.models.payment_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='physics_marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='qualification',
            field=models.CharField(blank=True, choices=[('12th', '12th'), ('Diploma', 'Diploma')], max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='reference_department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='reference_designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='reference_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admission',
            name='reference_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='skill_proof',
            field=models.FileField(blank=True, null=True, upload_to=app.models.vocational_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='tenth_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='tenth_total',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='twelfth_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='twelfth_total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='vocational_stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='year_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
