# Generated by Django 5.2.8 on 2025-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_paymentscreenshot_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='district',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, null=True),
        ),
    ]
