# Generated by Django 5.2.8 on 2025-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_admission_country_admission_district_admission_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='unique_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
