# Generated by Django 6.0.1 on 2026-01-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_activitylog_feepayment_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='app.followup'),
        ),
    ]
