# Generated by Django 6.0.1 on 2026-01-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_activitylog_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='had_paid',
            field=models.BooleanField(default=False),
        ),
    ]
