# Generated by Django 6.0.1 on 2026-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_admission_had_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
