# Generated by Django 6.0.1 on 2026-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_admission_diploma_percentage_admission_diploma_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='group_major',
            new_name='diploma_major',
        ),
        migrations.AddField(
            model_name='admission',
            name='twelfth_major',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
