# Generated by Django 6.0.1 on 2026-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_group_major_admission_diploma_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='twelfth_major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
