# Generated by Django 6.0.2 on 2026-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_admission_twelfth_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='Application_number',
            new_name='application_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admission_fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bus_needed',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='chemistry_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='community_cert',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='cutoff_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hostel_fee_amount',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hostel_needed',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='hostel_type',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='last_school',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='maths_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mess_type',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='physics_marks',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='register_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='skill_proof',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='tc',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='tenth_marksheet',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='tuition_fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='twelfth_marksheet',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='vocational_stream',
        ),
        migrations.AddField(
            model_name='admission',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='admission',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admission',
            name='address_line1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='address_line2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='allotment_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='balance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='caste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='concession_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('transport', 'Transport')], max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='fg_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='admission',
            name='other_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='paid_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='pmss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='portal_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='quota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='seeding_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admission',
            name='university_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='board',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='boarding_point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bus_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='college_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='community',
            field=models.CharField(blank=True, choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('DNC', 'DNC'), ('BCM', 'BCM'), ('SC', 'SC'), ('SCA', 'SCA'), ('ST', 'ST')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='hostel_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='medium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
