# Generated by Django 6.0.2 on 2026-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_application_number_admission_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_fg',
            field=models.BooleanField(default=False),
        ),
    ]
