# Generated by Django 6.0.2 on 2026-02-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_admission_is_fg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='address_line2',
        ),
    ]
