# Generated by Django 6.0.2 on 2026-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_address_line1_admission_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='diploma_major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
