# Generated by Django 6.0.2 on 2026-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_admission_diploma_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
