# Generated by Django 5.2.7 on 2026-02-05 17:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_admission_chemistry_marks_admission_cutoff_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='bus_needed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='bus_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_needed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='hostel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mess_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='skill_proof',
            field=models.FileField(blank=True, null=True, upload_to=app.models.vocational_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='vocational_stream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
