# Generated by Django 5.2.7 on 2026-02-05 17:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_admission_bus_needed_admission_bus_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='aadhaar',
            field=models.FileField(blank=True, null=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='community_cert',
            field=models.FileField(blank=True, null=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=app.models.photo_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='tc',
            field=models.FileField(blank=True, null=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='tenth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=app.models.certificate_upload_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='twelfth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=app.models.certificate_upload_path),
        ),
    ]
