# Generated by Django 6.0.2 on 2026-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_admission_aadhaar_admission_community_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='reference_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='reference_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='reference_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='reference_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
