# Generated by Django 6.0.2 on 2026-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_admission_reference_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='portal_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
