# Generated by Django 6.0.2 on 2026-02-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_admission_portal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='seven_five',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='twelth_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
