# Generated by Django 6.0.2 on 2026-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_admission_seven_five_admission_twelth_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('transport', 'Transport')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='level',
            field=models.CharField(blank=True, choices=[('ug', 'UG'), ('pg', 'PG'), ('le', 'LE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='qualification',
            field=models.CharField(blank=True, choices=[('12th', '12th'), ('Diploma', 'Diploma')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
