# Generated by Django 5.2.7 on 2026-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_admission_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_status',
            field=models.CharField(choices=[('enquired', 'Enquired'), ('admitted', 'Admitted'), ('discontinued', 'Discontinued'), ('left', 'Left')], default='enquired', max_length=20),
        ),
    ]
