# Generated by Django 5.2.7 on 2026-02-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_admission_admission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_department',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_designation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_mobile',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='relationship',
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='app.admission')),
            ],
        ),
    ]
