# Generated by Django 6.0.2 on 2026-02-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_admission_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='balance_fee',
            new_name='unpaid_fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admission_fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='pending_amount',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='tuition_fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='university_fee',
        ),
    ]
