# Generated by Django 5.2.7 on 2026-02-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_balance_fee_admission_unpaid_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
