# Generated by Django 5.2.7 on 2026-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_feepayment_remarks_feepayment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_status',
            field=models.CharField(choices=[('enquired', 'Enquired'), ('admitted', 'Admitted'), ('discontinued', 'Discontinued'), ('left', 'Left')], db_index=True, default='enquired', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='board',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='community',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='cutoff_marks',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='level',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
