# Generated by Django 6.0.2 on 2026-02-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='college_address1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='college_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='college_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='diploma_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='diploma_year_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
